#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost
if ynh_exec_warn_less yunohost service status $app >/dev/null 2>&1
then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing systemd service..." --weight=1

# Stop systemd service
ynh_systemd_action --service_name=$app --action="stop" --log_path="$data_dir/logs/freqtrade.log"

# Remove systemd service
if [ -e "/etc/systemd/system/$app.service" ]; then
    systemctl disable $app.service --quiet
    ynh_secure_remove --file="/etc/systemd/system/$app.service"
    systemctl daemon-reload
fi

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

if [ -e "/etc/logrotate.d/$app" ]; then
    ynh_secure_remove --file="/etc/logrotate.d/$app"
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

if [ -f "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then
    ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1
    ynh_secure_remove --file="/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_systemd_action --service_name=nginx --action=reload
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last