#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# STANDARD REMOVE
#=================================================

# Remove the service from the list of services known by YunoHost
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove $app
fi

# Stop and remove the systemd service
ynh_script_progression --message="Stopping and removing systemd service..." --weight=1
ynh_remove_systemd_config

# Remove the log files
ynh_script_progression --message="Removing logs..." --weight=1
ynh_remove_logrotate

# Remove nginx configuration (if exists)
if [ -f "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then
    ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1
    ynh_remove_nginx_config
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last